
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.mediawiki.name }}
  labels:
    app: {{.Values.mediawiki.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.mediawiki.name }}
  template:
    metadata:
      labels:
        app: {{.Values.mediawiki.name }}
    spec:
      containers:
      - name: {{.Values.mediawiki.name }}
        image: "{{.Values.mediawiki.image }}"
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: {{.Values.mysql.service.host }}
        - name: MYSQL_USER
          value: {{.Values.mysql.user }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Values.mysql.secretName }}
              key: password
        - name: MYSQL_DATABASE
          value: {{.Values.mysql.database }}
